### ISSUE TITLE
Reproduced result of TED15 zh-en

### ISSUE THREAD

**Issue by Blickwinkel1107** [idiap/HAN_NMT#10]
Hi,
I ran the scripts you provided in README.md, however i found my HANNMT get only 15.8 BLEU on IWSLT15.zh-en.
Moreover I found my pretraining sentence-level model get 16.1 BLEU on IWSLT15.zh-en.
I don't understand why the added context-learning components made translation worse, and I'm sure I strictly followed your cmd and scripts.
Can you please provide the your scripts or an illustration?
Thx.

**Comment by robotsp** [comment]
@Blickwinkel1107  did you solve the problem? I am coming across the same problem as yours.
