### ISSUE TITLE
Cohesion Evaluation

### ISSUE THREAD

**Issue by txAnnie** [idiap/HAN_NMT#2]
Hi, I wonder how to evaluate lexical cohesion according to Wong and Kit(2012)

**Comment by lmiculicich** [comment]
Hi, there is a short description in section 4.3 of the paper. Here some details about our implementation, please let me know if you have questions, remarks or comments:
- Filtering: filter out stop-words (nltk.corpus.stopwords.words('english')), and punctuation.
- Repetitions: apply steam to each word (nltk.stem.PorterStemmer) and count all repetitions. 
- Synsets:  Apply POS tagging (nltk.pos_tag) to the original sentence. Map the POS tag to 'N*'->'n', 'V*'->'v', 'J*'->'a', 'R*'->'r' or none. With the word and tag get the synset using (nltk.corpus.wordnet). If more than one synset is returned, I choose the first one. 
- Synonyms and near-synonyms: Using synset get "path_similarity" of a pair of words, and count if similarity is 1.
- Superordinate and collocation: with the word synsets get "lowest_common_hypernyms" of a pair of words, calculate similarity according (Wong and Kit, 2012), count if similarity is greater than 0.96.

**Comment by lmiculicich** [comment]
> Hi, I wonder how to evaluate lexical cohesion according to Wong and Kit(2012)

**Comment by txAnnie** [comment]
ok，thanks a lot
