### ISSUE TITLE
how to do with this: TypeError: __init__() got an unexpected keyword argument 'tensor_type'

### ISSUE THREAD

**Issue by karlgeorge** [idiap/HAN_NMT#5]
when i try to preprocess the data:
Traceback (most recent call last):
  File "preprocess.py", line 215, in <module>
    main()
  File "preprocess.py", line 202, in main
    fields = onmt.io.get_fields(opt.data_type, src_nfeats, tgt_nfeats)
  File "/home/newhdd/young/HAN_NMT/full_source/onmt/io/IO.py", line 61, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "/home/newhdd/young/HAN_NMT/full_source/onmt/io/TextDataset.py", line 240, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'tensor_type'
the python version is 2.7

**Comment by abhranil08** [comment]
how do i get this issue solved?

**Comment by lmiculicich** [comment]
I think has to do with the version of torchtext.data.Field. There is a similar issue here:
https://github.com/OpenNMT/OpenNMT-py/issues/767

However, the field "src_map" is not used for this model so can be omitted. Or change the values of make_src to float.

**Comment by vivi2053** [comment]
installing torchtext 0.2.1 solved this for me
