### ISSUE TITLE
Training HAN-jointly

### ISSUE THREAD

**Issue by zebcode** [idiap/HAN_NMT#7]
In the training procedure i have seen that we can train the HAN jointly using sentence level model through the HAN-encoder and HAN-decoder, but i didn't get where you use the HAN-decoder model for train the model jointly ?? So how we could use HAN-decoder model for training the model jointly?? And in source code files i didn't find any code for HAN-decoder model...

**Comment by lmiculicich** [comment]
I didn't use it here, the joint model starts with HAN-encoder. You could start it with HAN-decoder.
