### ISSUE TITLE
How to reproduce the results of zh-en TED？

### ISSUE THREAD

**Issue by procjx** [idiap/HAN_NMT#9]
I downloaded the zh-en TED dataset and run the code followed the README file, but could not reproduce the results reported in the paper, how could I reproduce the results?

**Comment by Blickwinkel1107** [comment]
Cannot reproduce either! I got BLEU=15.8 on IWSLT15.tst2010-2013, way too lower than the BLEU the author claimed in paper. However I am sure I use the same command mentioned in README.md :-(

**Comment by robotsp** [comment]
@procjx did you solve the problem? I have the same problem as you.
